In [1]:
import numpy as np
import math
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
w1 = np.array([[0.1,1.1],[6.8,7.7],[-3.5,-4.1],[2,2.7],[4.1,2.8],[3.1,5],[-0.8,-1.3],[0.9,1.2],[5,6.4],[3.9,4.0]])
w2 = np.array([[7.1,4.2],[-1.4,-4.3],[4.5,0],[6.3,1.6],[4.2,1.9],[1.4,-3.2],[2.4,-4],[2.5,-6.1],[8.4,3.7],[4.1,-2.2]])

w3 = np.array([[-3,-2.9],[0.5,8.7],[2.9,2.1],[-0.1,5.2],[-4,2.2],[-1.3,3.7],[-3.4,6.2],[-4.1,3.4],[-5.1,1.6],[1.9,5.1]])
w4 = np.array([[-2,-8.4],[-8.9,0.2],[-4.2,-7.7],[-8.5,-3.2],[-6.7,-4],[-0.5,-9.2],[-5.3,-6.7],[-8.7,-6.4],[-7.1,-9.7],[-8,-6.3]])

In [3]:
one = np.ones((10)).reshape(-1,1)
one.shape

(10, 1)

In [4]:
#增广
w1_t = np.append(w1,one, axis=1)
w2_t = np.append(w2,one, axis=1)
w3_t = np.append(w4,one, axis=1)
w4_t = np.append(w4,one, axis=1)

In [5]:
#权重向量a，学习率lr
a  = np.array((0,1,0)).reshape(1,-1)
lr = 0.5


In [6]:
W1 =np.append(w1_t,-w2_t,axis=0) #规范化
W2 =np.append(w3_t,-w2_t,axis=0) #规范化
W1.shape

(20, 3)

In [7]:
k = 0#迭代次数
for i in range(0,80):
    sg = np.trunc((1-np.sign(np.dot(W1,a.T)))/2) #判断ay乘机是否小于0
    A1 = W1*sg#
    C = np.sum(A1,axis=0).reshape(1,-1)
    print(a)
    a = a + lr*C
    if A1.min()>=0: #表示ay都大于等于0
        break
    k+=1    

[[0 1 0]]
[[-15.15  -7.4   -1.  ]]
[[-3.45 14.85  1.5 ]]
[[-18.6    6.45   0.5 ]]


In [8]:
w1[0:8,:]

array([[ 0.1,  1.1],
       [ 6.8,  7.7],
       [-3.5, -4.1],
       [ 2. ,  2.7],
       [ 4.1,  2.8],
       [ 3.1,  5. ],
       [-0.8, -1.3],
       [ 0.9,  1.2]])

In [9]:
X1 = np.append(w1[0:7,:].T,w2[0:7,:].T,axis=1)
X1.shape

(2, 14)

In [10]:
X1 = np.append(w1_t[0:8,:].T,w2_t[0:8,:].T,axis=1)
X2 = np.append(w3_t[0:8,:].T,w4_t[0:8,:].T,axis=1)
X_train = np.append(X1,X2,axis=1)
X_v = np.append(np.append(w1_t[8:10,:].T,w2_t[8:10,:].T,axis=1),np.append(w3_t[8:10,:].T,w4_t[8:10,:].T,axis=1),axis=1)
X_train.shape,X_v.shape

((3, 32), (3, 8))

In [11]:
W_ems = np.random.rand(4,2)
W_ems

array([[9.54117361e-01, 9.97194391e-01],
       [3.96958489e-01, 9.68409941e-02],
       [7.93132042e-04, 3.85103516e-01],
       [4.37857077e-01, 4.88715752e-01]])

In [12]:
y1 = np.ones((1,8))
y2 = np.zeros((3,8))
y1.shape,y2.shape

((1, 8), (3, 8))

In [13]:
y11 = np.append(y1,y2,axis=0)
y22 = np.insert(y2,1,y1,axis = 0)
y33 = np.insert(y2,2,y1,axis = 0)
y44 = np.insert(y2,3,y1,axis = 0)
y12 = np.append(y11,y22,axis = 1)
y34 = np.append(y33,y44,axis = 1)
Y_train = np.append(y12,y34,axis = 1)

In [14]:
W = np.dot(np.dot(np.linalg.inv(np.dot(X_train,X_train.T)+0.01),X_train),Y_train.T)


In [15]:
print(W.reshape(-1,4))

[[ 0.00609391  0.05719392 -0.0316472  -0.0316472 ]
 [ 0.05245566 -0.01633877 -0.01808472 -0.01808472]
 [ 0.39967837  0.2953755   0.15224149  0.15224149]]


In [16]:
X_v

array([[ 5. ,  3.9,  8.4,  4.1, -7.1, -8. , -7.1, -8. ],
       [ 6.4,  4. ,  3.7, -2.2, -9.7, -6.3, -9.7, -6.3],
       [ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ]])

In [17]:
y = np.dot(W.T,X_v)
y.T

array([[ 0.7658641 ,  0.476777  , -0.12173673, -0.12173673],
       [ 0.63326723,  0.45307673, -0.04352147, -0.04352147],
       [ 0.64495311,  0.71535101, -0.18050845, -0.18050845],
       [ 0.30926094,  0.56581587,  0.06227436,  0.06227436],
       [-0.15240823,  0.04778469,  0.55235839,  0.55235839],
       [ 0.02045649, -0.05924165,  0.51935282,  0.51935282],
       [-0.15240823,  0.04778469,  0.55235839,  0.55235839],
       [ 0.02045649, -0.05924165,  0.51935282,  0.51935282]])