In [1]:
import numpy as np

# 1.Numpy结构

In [2]:
array = [1,2,3,4,5]

In [3]:
type(array)

list

In [4]:
npar = np.array([1,2,3,4,5])

In [5]:
npar

array([1, 2, 3, 4, 5])

In [6]:
type(npar)

numpy.ndarray

In [7]:
npar.dtype

dtype('int32')

In [8]:
npar+1

array([2, 3, 4, 5, 6])

In [9]:
npar + npar

array([ 2,  4,  6,  8, 10])

In [10]:
npar * npar

array([ 1,  4,  9, 16, 25])

# 2.ndarray结构

In [11]:
list_ = [1,2,3,4.2]

In [12]:
array_= np.array(list_)

In [13]:
array_

array([1. , 2. , 3. , 4.2])

In [14]:
array_.dtype

dtype('float64')

In [15]:
array_.size

4

In [16]:
array_.ndim

1

In [17]:
array_.fill(1)

In [18]:
array_

array([1., 1., 1., 1.])

# 3.索引和切片

In [19]:
list_ = [1,2,3,4.0]
array_= np.array(list_)

In [20]:
array_[0]

1.0

In [21]:
array_[-1]

4.0

In [22]:
array_[0:2] #[*)

array([1., 2.])

In [23]:
array_[:-1]

array([1., 2., 3.])

In [24]:
array_[-3:]

array([2., 3., 4.])

In [25]:
array_ = np.array([[1,2,3.2],[4,5,6],[7,8,9]])
array_

array([[1. , 2. , 3.2],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [26]:
array_.shape

(3, 3)

In [27]:
array_.size

9

In [28]:
array_.ndim

2

In [29]:
array_[1,1]

5.0

In [30]:
array_[1,1]= 6.2

In [31]:
array_

array([[1. , 2. , 3.2],
       [4. , 6.2, 6. ],
       [7. , 8. , 9. ]])

In [32]:
array_[2]

array([7., 8., 9.])

In [33]:
array_[1:3]

array([[4. , 6.2, 6. ],
       [7. , 8. , 9. ]])

In [34]:
array_[:,0]

array([1., 4., 7.])

In [35]:
array_[:,1:3]

array([[2. , 3.2],
       [6.2, 6. ],
       [8. , 9. ]])

In [36]:
array_[0:2,1:3]

array([[2. , 3.2],
       [6.2, 6. ]])

In [37]:
array_2 = array_ #两者等价了，地址赋值了
array_2

array([[1. , 2. , 3.2],
       [4. , 6.2, 6. ],
       [7. , 8. , 9. ]])

In [38]:
array_2[1,1] = 0
array_2

array([[1. , 2. , 3.2],
       [4. , 0. , 6. ],
       [7. , 8. , 9. ]])

In [39]:
array_

array([[1. , 2. , 3.2],
       [4. , 0. , 6. ],
       [7. , 8. , 9. ]])

# 3.1数组赋值

In [40]:
array_2 = array_.copy()
array_2

array([[1. , 2. , 3.2],
       [4. , 0. , 6. ],
       [7. , 8. , 9. ]])

In [41]:
array_2[1,1] = 100
array_2

array([[  1. ,   2. ,   3.2],
       [  4. , 100. ,   6. ],
       [  7. ,   8. ,   9. ]])

In [42]:
array_ #这儿是两个数组

array([[1. , 2. , 3.2],
       [4. , 0. , 6. ],
       [7. , 8. , 9. ]])

# 3.2 大数组生成

In [43]:
array_ = np.arange(0,100)
array_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
array_ = np.arange(0,100,10)
array_

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
mask = np.array([1,2,0,5,0,6,0,8,9,1],dtype=bool)
mask

array([ True,  True, False,  True, False,  True, False,  True,  True,
        True])

In [46]:
array_[mask] #取出bool是Ture的array_

array([ 0, 10, 30, 50, 70, 80, 90])

# 3.3随机数

In [47]:
random_array = np.random.rand(10) #生成10个随机数
random_array

array([9.01505109e-02, 5.56103201e-02, 3.32555122e-04, 4.93047885e-01,
       2.91020828e-01, 5.74068142e-01, 5.07330739e-01, 1.80442316e-01,
       1.72221859e-01, 8.36334689e-01])

In [48]:
random_array = np.random.randint(-100,10) #生成1个-100-10的整数
random_array

3

In [49]:
random_array = np.random.randint(-100,100,size=(5,6)) #生成1个数组，范围-100-10的整数
random_array

array([[-28, -68,  57,  53, -43, -71],
       [-43, -86, -29,  23, -87, -14],
       [ 63, -24, -18, -43,  22,  40],
       [ 42,   6,  72, -35, -43,  27],
       [ 94, -59, -13,  84, -19, -92]])

In [50]:
np.sum(random_array) #整个数值之和

-232

In [51]:
np.sum(random_array,axis=0) #按列求和

array([ 128, -231,   69,   82, -170, -110])

In [52]:
np.sum(random_array,axis=1) #按行求和

array([-100, -236,   40,   69,   -5])

# 3.4.考虑维度

In [53]:
random_array.ndim

2

In [54]:
random_array = np.random.randint(-7,7,size=(3,6,4)) #生成1个数组，范围-100-10的整数
random_array

array([[[ 4, -3,  3, -6],
        [ 2,  2,  6,  3],
        [ 2,  2, -2, -7],
        [ 6,  3,  1,  5],
        [ 4,  5, -5,  6],
        [-3,  1, -2,  1]],

       [[ 4, -6, -6, -5],
        [ 4, -1,  6, -6],
        [ 6,  2, -2, -2],
        [-2,  4,  2, -5],
        [-3,  3,  6,  0],
        [-2,  2,  2,  6]],

       [[ 5, -1, -6, -6],
        [-4,  0, -3,  2],
        [-2, -3,  2, -5],
        [-5,  4, -4, -7],
        [-4,  3, -7,  0],
        [-6, -4,  2,  2]]])

In [55]:
np.sum(random_array,axis=0) #看成层，投影到z轴，留下x，y方向数值;size变成去掉该维度的大小

array([[ 13, -10,  -9, -17],
       [  2,   1,   9,  -1],
       [  6,   1,  -2, -14],
       [ -1,  11,  -1,  -7],
       [ -3,  11,  -6,   6],
       [-11,  -1,   2,   9]])

In [56]:
random_array[0,0,-1]

-6

In [57]:
np.sum(random_array,axis=1)

array([[ 15,  10,   1,   2],
       [  7,   4,   8, -12],
       [-16,  -1, -16, -14]])

In [58]:
np.sum(random_array,axis=2)

array([[ -2,  13,  -5,  15,  10,  -3],
       [-13,   3,   4,  -1,   6,   8],
       [ -8,  -5,  -8, -12,  -8,  -6]])

In [59]:
random_array = np.random.randint(1,7,size=(2,2))
random_array

array([[5, 2],
       [2, 4]])

In [60]:
random_array.prod() #各个数据元素之积

80

In [61]:
random_array.prod(axis=0)

array([10,  8])

In [62]:
random_array.prod(axis=1)

array([10,  8])

In [63]:
random_array.max()

5

In [64]:
random_array.max(axis = 1)

array([5, 4])

In [65]:
random_array.argmax() #最小值的索引，及位置

0

In [66]:
random_array.argmin(axis=1) #对于重复的最大值或最小值，选择第一个索引

array([1, 0], dtype=int64)

In [67]:
random_array.mean()#求均值

3.25

In [68]:
random_array = np.random.randint(-7,7,size=(3,6)) #生成1个数组，范围-100-10的整数
random_array

array([[ 5, -7, -4,  3, -5, -7],
       [-7, -6,  3, -7, -6,  4],
       [ 4,  5, -4, -7, -1,  4]])

In [69]:
np.sort(random_array)

array([[-7, -7, -5, -4,  3,  5],
       [-7, -7, -6, -6,  3,  4],
       [-7, -4, -1,  4,  4,  5]])

In [70]:
np.sort(random_array,axis=0)

array([[-7, -7, -4, -7, -6, -7],
       [ 4, -6, -4, -7, -5,  4],
       [ 5,  5,  3,  3, -1,  4]])

In [71]:
np.sort(random_array,axis=1) #等价于np.sort(random_array)

array([[-7, -7, -5, -4,  3,  5],
       [-7, -7, -6, -6,  3,  4],
       [-7, -4, -1,  4,  4,  5]])

In [72]:
np.argsort(random_array)

array([[1, 5, 4, 2, 3, 0],
       [0, 3, 1, 4, 2, 5],
       [3, 2, 4, 0, 5, 1]], dtype=int64)

In [73]:
np.argsort(random_array,axis=0)

array([[1, 0, 0, 1, 1, 0],
       [2, 1, 2, 2, 0, 1],
       [0, 2, 1, 0, 2, 2]], dtype=int64)

In [74]:
random_array.shape

(3, 6)

In [75]:
random_array.shape = 18 #注意和原来的数组，数值个数相同
random_array

array([ 5, -7, -4,  3, -5, -7, -7, -6,  3, -7, -6,  4,  4,  5, -4, -7, -1,
        4])

In [76]:
random_array.reshape(18,1)

array([[ 5],
       [-7],
       [-4],
       [ 3],
       [-5],
       [-7],
       [-7],
       [-6],
       [ 3],
       [-7],
       [-6],
       [ 4],
       [ 4],
       [ 5],
       [-4],
       [-7],
       [-1],
       [ 4]])

In [77]:
random_array.shape = 2,9

In [78]:
random_array

array([[ 5, -7, -4,  3, -5, -7, -7, -6,  3],
       [-7, -6,  4,  4,  5, -4, -7, -1,  4]])

In [79]:
random_array_2 = random_array[np.newaxis,:]#维度增加
random_array_2

array([[[ 5, -7, -4,  3, -5, -7, -7, -6,  3],
        [-7, -6,  4,  4,  5, -4, -7, -1,  4]]])

In [80]:
random_array_2.shape

(1, 2, 9)

In [81]:
random_array_2 = random_array[np.newaxis,:,np.newaxis]
random_array_2

array([[[[ 5, -7, -4,  3, -5, -7, -7, -6,  3]],

        [[-7, -6,  4,  4,  5, -4, -7, -1,  4]]]])

In [82]:
random_array_2.shape

(1, 2, 1, 9)

In [83]:
random_array

array([[ 5, -7, -4,  3, -5, -7, -7, -6,  3],
       [-7, -6,  4,  4,  5, -4, -7, -1,  4]])

In [84]:
random_array.shape

(2, 9)

In [85]:
random_array_2 = random_array_2.squeeze()

In [86]:
random_array_2.shape

(2, 9)

In [87]:
random_array_2.T

array([[ 5, -7],
       [-7, -6],
       [-4,  4],
       [ 3,  4],
       [-5,  5],
       [-7, -4],
       [-7, -7],
       [-6, -1],
       [ 3,  4]])

In [88]:
random_array_2.T.shape

(9, 2)

In [89]:
array1 = np.random.randint(10,size=(2,5))
array1

array([[3, 4, 3, 2, 9],
       [6, 6, 0, 9, 1]])

In [90]:
array1.size

10

In [91]:
array2 = np.random.randint(10,size=(2,5))
array2

array([[5, 8, 4, 4, 7],
       [0, 7, 3, 9, 6]])

In [92]:
array3 = np.concatenate((array1,array2)) #按行拼接
array3 

array([[3, 4, 3, 2, 9],
       [6, 6, 0, 9, 1],
       [5, 8, 4, 4, 7],
       [0, 7, 3, 9, 6]])

In [93]:
array3.shape

(4, 5)

In [95]:
array3 = np.concatenate((array1,array2),axis=0) #按行拼接
array3 

array([[8, 7, 0, 0, 4],
       [4, 3, 7, 2, 4],
       [3, 7, 6, 4, 3],
       [3, 6, 2, 3, 0]])

In [94]:
array3 = np.concatenate((array1,array2),axis=1) #按列拼接
array3 

array([[7, 6, 1, 4, 7, 1, 6, 1, 5, 2],
       [5, 9, 4, 7, 0, 6, 4, 7, 0, 6]])

In [95]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [96]:
x = np.arange(1,3)
y = np.arange(3,5)

In [97]:
x,y

(array([1, 2]), array([3, 4]))

In [98]:
x*y

array([3, 8])

In [99]:
np.multiply(x,y) #matlab的点乘

array([3, 8])

In [100]:
(x.T * y.T)

array([3, 8])

In [101]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
y = np.arange(1,7).reshape(2,3)
y

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
np.dot(x,y) #矩阵乘法

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
x,y

In [ ]:
x == y #矩阵对比